services:
  sql-pessoal:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_pessoal
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=b4seDuCr4t0#?
    ports:
      - "1434:1433"
    volumes:
      - sql_data_pessoal:/var/opt/mssql
    restart: always

volumes:
  sql_data_pessoal: